version: '3.8'

services:
  blopup-telegram-bot:
    build: .
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      DOMAIN: ${DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.blopup-telegram-bot.rule=Host(`${DOMAIN}`) && PathPrefix(`/telegram-bot`)
