### send a message from the bot to a user

# curl -X POST
#-H 'Content-Type: application/json'
#-d '{"chat_id": "123456789", "text": "Reply from the bot to your TEST sent via curl"}'
#https://api.telegram.org/bot$BOT_TOKEN/sendMessage
# token has been saved to Bitwarden
POST https://api.telegram.org/bot{{token}}/sendMessage
Content-Type: application/json

{
  "chat_id": "-4130902917",
  "text": "Hola grupo!"
}

### set new commands for the bot
POST https://api.telegram.org/bot{{token}}/setMyCommands
accept: application/json
Content-Type: application/json

{
  "commands": [
    {
      "command": "/chatid",
      "description": "message yourself through the api!"
    }
  ]
}



### get updates
GET https://api.telegram.org/bot{{token}}/getUpdates
accept: application/json
Content-Type: application/json



