name: Deploy Telegram Bot

on:
  workflow_dispatch:

env:
  SSH_USER: ${{ secrets.SSH_USER }}

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: gradle
          distribution: 'temurin'
      - name: Build
        run: gradle build
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/remote.key
          chmod 600 ~/.ssh/remote.key
          cat >>~/.ssh/config <<END
          Host remote
            HostName blopup.upc.edu
            User $SSH_USER
            IdentityFile ~/.ssh/remote.key
            StrictHostKeyChecking no
          END
      - name: Copy deploy files to remote host
        run: |
          scp docker-compose-telegram.yaml remote:/home/$SSH_USER
          scp Dockerfile remote:/home/$SSH_USER
          scp build/libs/blopup.telegram.bot-1.0.jar remote:/home/$SSH_USER
      - name: Set telegram bot token
        run: |          
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" > .env
          scp .env remote:/home/$SSH_USER
      - name: Delete previous instances
        run: ssh remote docker-compose -f docker-compose-telegram.yaml down
      - name: Deploy to non production environments
        run: ssh remote docker-compose -f docker-compose-telegram.yaml up -d --build
      - name: Remove sensitive files
        run: |
          ssh remote rm /home/$SSH_USER/.env
          ssh remote rm /home/$SSH_USER/Dockerfile
          ssh remote rm /home/$SSH_USER/blopup.telegram.bot-1.0.jar
          ssh remote rm /home/$SSH_USER/docker-compose-telegram.yaml
