name: Deploy to non production environments

on:
  workflow_dispatch:

env:
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_KEY: ${{ secrets.SSH_NON_PROD_PRIVATE_KEY }}
  ENV: blopup-dev.upc.edu

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: gradle
          distribution: 'temurin'
      - name: Build
        run: gradle build
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/remote.key
          chmod 600 ~/.ssh/remote.key
          cat >>~/.ssh/config <<END
          Host remote
            HostName $ENV
            User $SSH_USER
            IdentityFile ~/.ssh/remote.key
            StrictHostKeyChecking no
          END
      - name: Copy deploy files to remote host
        run: |
          scp docker-compose-telegram.yaml remote:/home/$SSH_USER
          scp Dockerfile remote:/home/$SSH_USER
          scp build/libs/blopup.telegram.bot-1.0.jar remote:/home/$SSH_USER
      - name: Set environment variables
        run: |
          ssh remote cat >>~/.env <<END
          ssh remote TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
          ssh remote END
      - name: Deploy to non production environments
        run: ssh remote docker-compose -f docker-compose-telegram.yaml up -d --build && docker ps