name: Deploy to non production environments

on:
  workflow_dispatch:

env:
  SSH_USER: ${{ secrets.SSH_USER }}
  ENV: blopup-dev.upc.edu

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name Build
      - run: gradle build
      - name: Configure SSH
        env:
          SSH_KEY: ${{ secrets.NON_PROD_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/remote.key
          chmod 600 ~/.ssh/remote.key
          cat >>~/.ssh/config <<END
          Host remote
            HostName $ENV
            User $SSH_USER
            IdentityFile ~/.ssh/remote.key
            StrictHostKeyChecking no
          END
      - name: Deploy to non production environments
        run: ssh remote export TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} && docker-compose up -d --build
      


